### ISSUE TITLE
AWS AppStream 2.0 Dashboard Questions

### ISSUE THREAD

**Issue by Ayushyadav19** [aws-samples/euc-toolkit#1]
Hi,
I have started using EUC-tookit for administering AWS AppStream 2.0. I have a few questions related to the dashboard:-

1. How the dashboard will get auto refresh whenever the AppStream sessions get started or ended?
2. Is there any way we can get information related to the apps used by the sessions?
3. How we can measure the client latency when connecting to AppStream sessions?
4. How we can manage the sessions in bulk?
5. Can we see a future enhancement for all the optional functionalities similar to the workspaces in AppStream2.0?

Thanks
Ayush

**Comment by morgnza** [comment]
Hey there Ayush, thanks for using the toolkit. I have added responses to the correlating questions below. Let me know if you have any follow ups.
1. Currently the only way to refresh the data in the AppStream window is to call the Get-AppStreamSessions function. This can be done through an added button and will be something review for our next version release.
2. For that, you will want to use [AppStream Usage Reports](https://docs.aws.amazon.com/appstream2/latest/developerguide/configure-usage-reports.html). Here is a [blog](https://aws.amazon.com/blogs/desktop-and-application-streaming/analyze-your-amazon-appstream-2-0-usage-reports-using-amazon-athena-and-amazon-quicksight/) covering how you can use them to make a dashboard. 
3. Client latency is not something tracked within the AppStream service so there currently is no way to pull it into the toolkit without a custom solution.
4. Currently we do not have logic in the function to select multiple, however that is something we can review for the next release. Similar functionality is in the WorkSpaces window. 
5. Much of the functionality was prioritized by customer feedback which focused on WorkSpaces. That said, we do plan to make the AppStream interface better in the future. 

If you cant wait for the next release, many of these things can be added manually if you are familiar with PowerShell.

**Comment by uncleVanyo** [comment]
Toolkit works fine but when I try to terminate a workspace nothing happens. The App gives the ok but the machine is not terminated. Any advice?

**Comment by morgnza** [comment]
Hey there! Thank you for raising this issue. This is a bug that has been addressed for our release planned for next week. In the meantime, selecting a single WorkSpace on the Bulk tab will successfully terminate.
