### ISSUE TITLE
Labeling issue in EUCToolkit-MainGUI.xml

### ISSUE THREAD

**Issue by davisdre** [aws-samples/euc-toolkit#3]
First let me state, thank you for this utility tool. Magnificent work!

I would submit for bug that I noticed.

**A reproducible test case or series of steps:**
- Run in a environment that has PCOIP workspaces.
![Screenshot 2023-11-15 212042](https://github.com/aws-samples/euc-toolkit/assets/18203393/349c7759-11a3-437e-be59-60822257e625)

**The version of our code being used:**
- Version 1.3

**Any modifications you've made relevant to the bug:**
- None. All original code.

**Anything unusual about your environment or deployment**
- Nothing Unusual.

**Comment by davisdre** [comment]
If you correct label names **lblBulkPCOIPCounter** and **lblBulkWSPCounter** in the **Assets/EUCToolkit-MainGUI.xml** you get correct labeling:
![Screenshot 2023-11-15 212303](https://github.com/aws-samples/euc-toolkit/assets/18203393/f14b54ab-94d1-4c4a-a1a3-abfd7fa61ec7)

**Comment by morgnza** [comment]
Thank you for raising this bug and patching it! Happy to hear you like the toolkit. Keep a look out for updates and improvements in the future.
